# Generated by Django 5.0 on 2024-03-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_country',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Client_country', 'verbose_name_plural': 'Client_country'},
        ),
        migrations.AlterModelOptions(
            name='client_requests',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Client_requests', 'verbose_name_plural': 'Client_requests'},
        ),
        migrations.AlterModelOptions(
            name='employee_model',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Employee_model', 'verbose_name_plural': 'Employee_model'},
        ),
        migrations.AlterModelOptions(
            name='four_pages_model',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Four_pages_model', 'verbose_name_plural': 'Four_pages_models'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='service_name',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Service_name', 'verbose_name_plural': 'Service_name'},
        ),
        migrations.AlterModelOptions(
            name='service_offers',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Service_offers', 'verbose_name_plural': 'Service_offers'},
        ),
        migrations.AlterModelOptions(
            name='template_web_model',
            options={'managed': True, 'ordering': ('pk',), 'verbose_name': 'Template_web_model', 'verbose_name_plural': 'Template_web_model'},
        ),
    ]
