# Generated by Django 5.0 on 2024-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_model',
            name='img_bkg',
            field=models.ImageField(default='user_bkg_1.jpg', upload_to='emp_img'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_type',
            field=models.CharField(choices=[('Paid SOCIAL MEDIA MARKETING ', 'Paid SOCIAL MEDIA MARKETING '), ('Content marketing', 'Content marketing'), ('Web development And Web design', 'Web development And Web design'), ('Full service marketing agencies', 'Full service marketing agencies'), ('E-COMMERCE SOLUTIONS', 'E-COMMERCE SOLUTIONS'), ('Advertising', 'Advertising'), ('Email marketing,', 'Email marketing,'), ('SEO branding', 'SEO branding'), ('And more', 'And more')], default=('Web development And Web design', 'Web development And Web design'), max_length=50, verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='service_offers',
            name='serv_offer',
            field=models.CharField(blank=True, choices=[('Paid SOCIAL MEDIA MARKETING ', 'Paid SOCIAL MEDIA MARKETING '), ('Content marketing', 'Content marketing'), ('Web development And Web design', 'Web development And Web design'), ('Full service marketing agencies', 'Full service marketing agencies'), ('E-COMMERCE SOLUTIONS', 'E-COMMERCE SOLUTIONS'), ('Advertising', 'Advertising'), ('Email marketing,', 'Email marketing,'), ('SEO branding', 'SEO branding'), ('And more', 'And more')], default=('Web development And Web design', 'Web development And Web design'), max_length=50, null=True, verbose_name='servic offer for'),
        ),
    ]
